name: Manage Windows Host with Ansible via WSL

on:
  push:
    branches:
      - main

jobs:
  ansible-wsl:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up WSL
      uses: Vampire/setup-wsl@v3

    - name: Run Ansible Playbook
      run: |
        # Install Ansible
        sudo apt update
        sudo apt install -y ansible
        # Create inventory file
        echo "[windows]" > inventory.ini
        echo "localhost ansible_connection=local" >> inventory.ini

        # Write the Ansible playbook to manage the Windows host
        echo "---" > playbook.yml
        echo "- name: Test Ansible on Windows Host" >> playbook.yml
        echo "  hosts: windows" >> playbook.yml
        echo "  tasks:" >> playbook.yml
        echo "  - name: Echo hostname" >> playbook.yml
        echo "    win_command: hostname" >> playbook.yml
        echo "    register: result" >> playbook.yml
        echo "  - name: Output hostname" >> playbook.yml
        echo "    debug:" >> playbook.yml
        echo "      msg: \"Windows hostname is {{ result.stdout }}\"" >> playbook.yml

        # Run the playbook
        ansible-playbook -i inventory.ini playbook.yml
      shell: wsl-bash {0}
