name: Manage Windows Host with Ansible via WSL

on:
  push:
    branches:
      - main

jobs:
  ansible-wsl:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - uses: devops37/ssh-win-from-wsl@v1

    - name: Install Python3 on wsl
      shell: wsl-bash {0}
      run: |
        sudo apt-get update
        sudo apt-get -y install python3 python3-pip
        python3 -m pip install ansible molecule

    - name: Run tests in wsl
      shell: wsl-bash {0}
      run: |
          echo $PATH
          pwd
          ls -l /mnt/d/ || true
          ls -l /mnt/d/a || true
          molecule --version
